name: PaperTrader

on:
  schedule:
    - cron: "*/5 * * * *"   # toutes les 5 minutes (UTC)
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run paper trader
        run: |
          python paper_trader.py

      - name: Commit & push outputs
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add out/*.csv state.json || true
          git commit -m "chore: update logs $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || echo "No changes"
          git push
